# MySQL
[mysql]
host = localhost
user = root
password = 1wuqingtieshou
database = FA-ops-rag

# Redis
[redis]
host = localhost
port = 6379
password = 1234
database = 0

#Milvus
[milvus]
host = localhsot
port = 19530
database_name = FA
collection_name = farag_final

#LLM配置
[llm]
model = qwen-plus
dashscope_api_key = sk-*********
dashscope_base_url = https://dashscope.a;oyuncs.com/compatible-mode/v1

#检索策略配置
[retrieval]
parent_chunk_size = 1200
child_chunk_size = 300
chunk_overlap = 50
retrieval_k = 3
candidate _m =2

#问答类配置
[app]
valid_sources = ["java","ops","fa","python","ita","wi","vag","ha","hdc"]
# 日志配置
[logger]
log_file = ../logs/app.log